/**
 * agent.ts
 *
 * Lightweight, transparent detection of whether a change was likely generated by an
 * AI coding agent. It is a flag, not a judgment of intent, and it always returns the
 * matched signals so the flag is explainable rather than a black box.
 *
 * Metadata is supplied by the CI environment (the GitHub Action sets PRODGATE_* env
 * or passes flags). Prodgate does not fetch anything itself.
 */

export type AgentMetadata = {
  author?: string
  branch?: string
  commitMessages?: string
  prBody?: string
}

export type AgentInfo = { likelyAgent: boolean; signals: string[] }

const AGENT_RE = /\b(claude|cursor|copilot|devin|aider|codex|sweep|tabnine|ona)\b|\bgpt-?[0-9]?\b/i
const BOT_LOGIN_RE = /\[bot\]$|-bot$|^bot-|cursor|devin|sweep|claude|copilot/i
const BRANCH_RE = /^(cursor|claude|devin|aider|copilot|codex|sweep|bot|ai)[\/-]/i

export function detectAgent(meta: AgentMetadata): AgentInfo {
  const signals: string[] = []
  const commits = meta.commitMessages ?? ''

  // Co-Authored-By trailers (Claude Code, Cursor, etc. stamp these).
  const trailers = commits.match(/Co-Authored-By:[^\n]+/gi) ?? []
  for (const t of trailers) {
    if (AGENT_RE.test(t)) {
      signals.push('co-author trailer: ' + t.replace(/Co-Authored-By:\s*/i, '').trim())
      break
    }
  }

  if (meta.author && (AGENT_RE.test(meta.author) || BOT_LOGIN_RE.test(meta.author))) {
    signals.push('author looks like an agent or bot: ' + meta.author)
  }
  if (meta.branch && BRANCH_RE.test(meta.branch)) {
    signals.push('branch name signals an agent: ' + meta.branch)
  }
  if (meta.prBody && AGENT_RE.test(meta.prBody)) {
    signals.push('PR description references an AI agent')
  }
  if (signals.length === 0 && commits && AGENT_RE.test(commits)) {
    signals.push('commit message references an AI agent')
  }

  return { likelyAgent: signals.length > 0, signals }
}
